shellEmulator: true

trustPolicy: no-downgrade
patchedDependencies:
  '@dcloudio/uni-ui': patches/@dcloudio__uni-ui.patch

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - esbuild
